#------------- PACKAGE MANAGEMENT -----------------
alias pacup='sudo pacman -Syu'
alias pacrm='sudo pacman -Rns'

#------------- GIT -----------------
# status & inspection
alias gst='git status -sb'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --oneline --graph --decorate -20'

# staging & committing
alias ga='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias grs='git restore .'

# branches
alias gb='git branch --list'
alias gsw='git switch'
alias gsc='git switch -c'

# remote
alias gp='git push'
alias gpl='git pull'
alias gf='git fetch'

#------------- NAVIGATION -----------------
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'
alias -- -='cd -'          # jump to previous directory

#------------- LISTING -----------------
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -altr'        # sort by time, newest last

#------------- SAFETY NETS -----------------
alias rm='rm -i'           # confirm before deleting
alias rmd='rm -rf'         # delete directory
alias cp='cp -i'           # confirm before overwrite
alias mv='mv -i'           # confirm before overwrite
alias mkdir='mkdir -pv'    # create parent dirs, verbose

#------------- SYSTEM INFO -----------------
alias df='df -h'           # human-readable sizes
alias du='du -h'
alias free='free -h'
alias path='echo -e ${PATH//:/\\n}'   # print PATH, one entry per line

#------------- MISC -----------------
alias h='history'
alias c='clear'
alias reload='source ~/.bashrc'
alias grep='grep --color=auto'
alias trim='sudo fstrim -va'
alias usage='sudo intel_gpu_top'
alias cleanshistory='history -c && history -w && truncate -s 0 "$HOME/.bash_history"'
